CREATE TABLE tb_users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  role ENUM('ADMIN','EMPLOYEE_WORKER','EMPLOYEE_MANAGER') NOT NULL
);

CREATE TABLE tb_employees (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id BIGINT UNIQUE,
    CONSTRAINT fk_user_employees FOREIGN KEY (user_id) REFERENCES tb_users (id)
);